### ISSUE TITLE
[FEATURE] Better error reporting

### ISSUE THREAD

**Issue by tsteuwer** [npm/ssri#9]
# What / Why

> It's very hard to track what package's checksum don't match.

## When
When npm installing you get an error that checksum X doesn't equal Y. But as a user installing npm packages, I have no idea what package that is or where to begin even looking at what packages are affected by this.

```
troy.steuwer$ npm i
Unhandled rejection Error: sha1-XdLz2PU4Q96X5WEv0OKThCSSeMk= integrity checksum failed when using sha1: wanted sha1-XdLz2PU4Q96X5WEv0OKThCSSeMk= but got sha512-SgGTC13n8IEewBTuX1rPMF7C8q7DAxvLdvch9hSknGYow/+/fqiw3umKSj3QrPcLwjkKmhZ2s4/KiuWthKf1vg== sha1-IE9YlDrHDPZbo29tfhu7U6fOWqI=. (177354 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
    at Transform.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

## Where
* n/a

### Current Behavior
* It just tells you checksums on something don't match.

### Expected Behavior
* Displays the checksums don't match on a specific package and what exactly that package is.

## Who
* n/a

## References
* n/a

**Comment by isaacs** [comment]
Once we move to the new version of Pacote and are doing installs with Arborist, the errors will always be decorated with the package _id and other info.  (And it won't just be some arbitrary failed promise, it'll actually be caught and reported.)

We already have extensive tests around this for the versions of SSRI, cacache, and Pacote that target npm v7.  Unfortunately, there isn't really any way to get there with Pacote v9 without massive refactoring (which is why Pacote 10 is pretty much a bottoms-up rewrite).

Since this is already fixed in npm v7, and prohibitively expensive to fix in npm v6, and npm v7 is right around the corner, I'm gonna close this.  Something between `WONTFIX` and `FIXED` :)
